version: "3.7"

services:
  remix:
    image: sugggest
    container_name: sugggest-remix
    restart: unless-stopped
    volumes:
      - ./src/gateways/prisma/db:/usr/src/sugggest/src/gateways/prisma/db
      - ./.env:/usr/src/sugggest/.env
    # Expose ports without publishing them to the host machine - they’ll only be accessible to linked services.
    expose:
      - 3000

  studio:
    image: sugggest
    container_name: sugggest-studio
    command: "yarn studio"
    restart: unless-stopped
    volumes:
      - ./src/gateways/prisma/db:/usr/src/sugggest/src/gateways/prisma/db
      - ./.env:/usr/src/sugggest/.env
    # Expose ports without publishing them to the host machine - they’ll only be accessible to linked services.
    expose:
      - 5555

  nginx:
    image: nginx
    restart: unless-stopped
    container_name: sugggest-proxy
    volumes:
      - ./src/infra/log/nginx:/var/log/nginx
      - ./src/infra/certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
      - ./src/infra/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./src/infra/.htpasswd:/etc/apache2/.htpasswd 
    ports:
      - 80:80
      - 443:443
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - remix

  certbot:
    image: certbot/certbot
    container_name: sugggest-certbot
    restart: unless-stopped
    volumes:
      - ./src/infra/certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;'"

volumes:
  certbot_www:
